# Generated by Django 3.2.4 on 2021-06-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='acessos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
